log:
  level: INFO

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"  

tls:
  certificates:
    - certFile: "etc/certs/kinodev.crt"
      keyFile: "etc/certs/kinodev.key"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik"
    watch: true  




