log:
  level: INFO

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
providers:
  docker:
    exposedByDefault: false


# tls:
#   certificates:
#     - certFile: "/certs/cert.crt"
#       keyFile: "/certs/cert.key"

