USE kinodev_local;

-- Moovies
USE kinodev_local;

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1001, 'Embers of the Crown', 'Set in a crumbling empire, Embers of the Crown follows a young noble whose honor is tested amid court intrigues and dangerous betrayals. Amid lavish banquets and secret alliances, he struggles to reconcile his family’s shattered legacy with the demands of a turbulent era. Every whispered conversation and covert meeting reveals hidden motives that could upend a fragile order. 
As rival factions collide and forbidden passions ignite hope, his journey becomes a quest for redemption. Against a backdrop of decaying palaces and vivid cultural rituals, the film explores the price of ambition and the enduring power of resilience in a world where every decision shapes history.', '2025-02-03', 108, 'http://images.kinodev.localhost/1001.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1002, 'Whispers of the Throne', 'Inside a lavish, yet perilous palace, Whispers of the Throne follows a cunning diplomat entangled in secret plots and dangerous liaisons. In candlelit corridors and amidst sumptuous feasts, every hushed conversation hints at betrayal and shifting loyalties, challenging his personal code of honor and duty.
As conspiracies deepen and ancient grudges resurface, the film paints a vivid portrait of a society on the brink of collapse. With intricate costumes and a stirring musical score, his struggle becomes a timeless exploration of ambition, sacrifice, and the cost of loyalty in a realm where every decision echoes through time.', '2024-03-11', 119, 'http://images.kinodev.localhost/1002.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1003, 'Shattered Reins', 'In a time of revolutionary change, Shattered Reins follows a defiant young leader wrestling with the collapse of traditional power. Faced with betrayal and unexpected alliances, he embarks on a quest to unite a fractured people, each act of defiance lighting the spark of change amid chaos.
Against a backdrop of epic battles and secret pacts, the film blends personal tragedy with historic upheaval. Detailed depictions of crumbling citadels and intimate moments of loss reveal a poignant narrative where even the shattering of old reins can pave the way for a new era of hope and unity.', '2023-11-21', 131, 'http://images.kinodev.localhost/1003.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1004, 'Legacy of Ashes', 'Legacy of Ashes tells the story of a once-proud family determined to reclaim lost honor after the ravages of war and betrayal. As they navigate a land scarred by conflict, each member confronts painful memories amidst decaying ruins and remnants of faded glory, sparking a journey toward redemption.
In a narrative interwoven with political intrigue and personal sacrifice, every secret uncovered and sacrifice made becomes a stepping stone toward renewal. The film’s evocative imagery and heartfelt moments illustrate that even from the ashes of despair, a new legacy can emerge—one defined by courage and the will to rebuild.', '2024-07-15', 118, 'http://images.kinodev.localhost/1004.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1005, 'Echoes of Valor', 'In Echoes of Valor, a battle-hardened warrior carries the weight of lost comrades and past glories across endless battlefields. His quest for redemption takes him through blood-stained clashes and quiet moments of introspection, where every echo of valor serves as a reminder of the cost of honor.
The film weaves grand war sequences with personal reflections, creating a powerful narrative of courage and inner strength. As he confronts both external foes and his own doubts, his journey becomes a stirring tribute to the enduring spirit of those who rise above fear to forge their destiny.', '2022-10-17', 138, 'http://images.kinodev.localhost/1005.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1006, 'Starlight Odyssey', 'Set in a future where interstellar travel is commonplace, Starlight Odyssey follows a diverse crew on a daring mission into unexplored galaxies. Their journey through cosmic storms and mysterious nebulae unravels clues about ancient alien secrets that challenge everything they know about the universe.
Amid mounting tensions and hidden agendas, each discovery forces the crew to confront both external dangers and their inner vulnerabilities. With breathtaking views of distant stars and swirling galaxies, the film is a meditation on identity, destiny, and the eternal wonder of exploring the great unknown.', '2024-07-22', 107, 'http://images.kinodev.localhost/1006.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1007, 'Celestial Frontier', 'Celestial Frontier thrusts a group of pioneers into the uncharted regions of space, where Earth’s survival hangs in the balance. Their mission leads them to alien landscapes and mysterious phenomena that test their scientific resolve and human spirit, as they search for a new beginning.
Amid cosmic dangers and unexpected alliances, the explorers face both external threats and personal conflicts. Vivid depictions of barren moons and radiant alien worlds set the stage for a gripping narrative where each step forward redefines hope and the very future of humanity.', '2025-01-01', 136, 'http://images.kinodev.localhost/1007.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1008, 'Nebula’s Edge', 'In Nebula’s Edge, a small crew ventures into a dazzling nebula where the laws of physics and reality blur. Their scientific expedition takes an unexpected turn as cosmic anomalies and hostile encounters reveal hints of a long-forgotten alien civilization lurking within the swirling mists.
The film balances scientific curiosity with raw human emotion as the crew battles isolation and fear amid vibrant, shifting colors of interstellar wonder. Every discovery within the nebula forces them to confront the mysteries of existence and their own place in the vast, enigmatic cosmos.', '2025-02-15', 118, 'http://images.kinodev.localhost/1008.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1009, 'Galactic Reverie', 'Galactic Reverie follows a visionary scientist and her eclectic crew as they investigate inexplicable cosmic phenomena that defy conventional wisdom. Their journey takes them through mesmerizing star systems and encounters with otherworldly events that challenge the very fabric of physics.As personal rivalries and unexpected bonds form amid the vast silence of space, the film offers a reflective narrative on the nature of consciousness and destiny. Each celestial encounter serves as a metaphor for the inner journeys of the characters, melding wonder with the search for deeper meaning.', '2025-02-11', 139, 'http://images.kinodev.localhost/1009.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1010, 'Orbit of Destiny', 'Amid a future of cosmic colonization, Orbit of Destiny charts the journey of a determined crew on a mission to establish a new home on an uncharted planet. Their voyage through the void is fraught with mysterious anomalies and unforeseen challenges that test both their science and resolve.Set against surreal planetary vistas and the stark beauty of orbiting space stations, the film intertwines high-stakes adventure with quiet introspection. Each twist of fate redefines destiny, as the crew learns that forging a new future among the stars requires both unity and unwavering hope.', '2025-02-21', 104, 'http://images.kinodev.localhost/1010.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1011, 'Midnight Wraith', 'In the silent depths of a forgotten town, Midnight Wraith follows a group of strangers drawn to an abandoned mansion haunted by a spectral presence. As darkness falls, eerie sounds, flickering lights, and ghostly apparitions blur the line between nightmare and reality, revealing a sinister history hidden within its walls.
The tension builds with every creaking floorboard and shadowed corridor, as each character confronts not only the supernatural but also their own buried fears. The film’s chilling atmosphere and haunting score create an experience where the true terror may lie in the echoes of past tragedies as much as in the ghostly figure that stalks the night.', '2025-02-07', 132, 'http://images.kinodev.localhost/1011.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1012, 'Haunted Dominion', 'Haunted Dominion centers on a family that moves into a decaying manor, seeking refuge from personal demons, only to discover the estate is ruled by a malevolent force. As night descends, unexplained sounds, shifting shadows, and unnerving visions unsettle their every moment, exposing dark secrets of the manor’s past.
As the boundaries between the living and the dead blur, the family’s unraveling reality becomes a battle against both supernatural horrors and their own inner turmoil. The film expertly combines claustrophobic tension with spectral dread, crafting a narrative where every whispered rumor deepens the impending sense of doom.', '2025-02-10', 117, 'http://images.kinodev.localhost/1012.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1013, 'Grim Shadows', 'In a remote village shrouded in perpetual twilight, Grim Shadows tells a harrowing tale of ancient curses and vengeful spirits. When inexplicable events begin to terrorize the community, an intrepid investigator arrives to uncover long-hidden secrets that intertwine myth and reality in chilling ways.
Every unsettling encounter and mysterious symbol amplifies the pervasive dread, as the villagers confront a legacy of fear that has haunted them for generations. The film’s stark visuals and relentless atmosphere create a sense of isolation where the true horror lies in the blurred boundary between legend and the present.', '2023-05-11', 120, 'http://images.kinodev.localhost/1013.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1014, 'Eclipse of Fear', 'When a rare celestial event plunges a small town into unnatural darkness, Eclipse of Fear unravels a terrifying story where cosmic mystery meets personal nightmares. As an eerie eclipse descends, strange visions and disembodied sounds unsettle the town, awakening a dormant curse that binds their fate to the skies.
The narrative weaves together individual terror and communal secrets, as each resident must confront both supernatural forces and their own dark pasts. With every shadow lengthened by the eclipse, the film builds a relentless atmosphere of dread, questioning whether the true horror is of the cosmos or the hearts of men.', '2024-08-16', 117, 'http://images.kinodev.localhost/1014.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1015, 'Nightmare’s Veil', 'In Nightmare’s Veil, a tormented artist retreats to an isolated manor in search of solace, only to find the estate shrouded in a sinister mist that distorts reality. As night falls, his dreams and waking life blur into a tapestry of disturbing visions and haunting apparitions that unsettle his very soul.
The manor becomes a labyrinth of eerie corridors and unsettling memories, where every flicker of light stokes his inner demons. As the veil between dream and reality grows thinner, the artist must confront the terror hidden within his own mind, crafting a psychological horror that lingers long after the credits roll.', '2020-10-15', 115, 'http://images.kinodev.localhost/1015.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1016, 'Love in Laughter', 'Set against the vibrant backdrop of a bustling city, Love in Laughter follows two unlikely souls whose lives intertwine through a series of humorous misadventures. A spilled coffee here and an impromptu street performance there spark a connection that turns everyday mishaps into moments of genuine affection.
Balancing witty banter with sincere vulnerability, the film captures how laughter can bridge differences and heal old wounds. Against lively urban scenes and playful dialogue, their unfolding romance is a heartwarming celebration of life’s delightful surprises and the unpredictable magic of love.', '2005-05-04', 116, 'http://images.kinodev.localhost/1016.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1017, 'Charming Mishaps', 'In a quaint small town, Charming Mishaps tells the story of two individuals whose paths continually cross through a series of comical, yet endearing, accidents. From mix-ups at local festivals to quirky encounters at neighborhood cafés, each mishap draws them closer, unveiling hidden layers of warmth and humor.
With engaging dialogue and a light-hearted tone, the film celebrates the beauty of imperfection. Every awkward moment becomes a stepping stone toward discovering that real romance is born from shared laughter and the serendipity of everyday life.', '2024-10-17', 117, 'http://images.kinodev.localhost/1017.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1018, 'Hearts Unscripted', 'Hearts Unscripted follows two people whose orderly lives are turned upside down by a series of spontaneous encounters. Unplanned adventures in sunlit plazas and unexpected conversations in rainy alleys spark a connection that feels both unpredictable and deeply genuine.
Blending witty repartee with moments of heartfelt introspection, the film shows that the best love stories are written by chance. Against dynamic cityscapes and a soulful soundtrack, each unscripted moment reveals that true romance blossoms when life’s surprises are embraced.', '2024-10-18', 118, 'http://images.kinodev.localhost/1018.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1019, 'Serendipity Smile', 'In the sunlit corridors of a vibrant city, Serendipity Smile follows two strangers brought together by a string of delightful coincidences. A mistaken text, a chance meeting in the park, and quirky local events gradually weave a tapestry of unexpected connection and genuine warmth.
The film uses playful dialogue and charming urban backdrops to show how a single smile can spark a lifelong romance. Each shared laugh and serendipitous encounter transforms ordinary days into a celebration of hope, reminding us that love often arrives when we least expect it.', '2025-02-01', 119, 'http://images.kinodev.localhost/1019.png');

INSERT INTO `kinodev_local`.`Movies` (`Id`, `Name`, `Description`, `ReleaseDate`, `Duration`, `Url`) VALUES (1020, 'Whimsical Hearts', 'Whimsical Hearts is a playful celebration of modern romance, following a quirky duo whose lives are filled with unexpected adventures. From spontaneous rooftop dances to humorous art gallery mishaps, every encounter adds a burst of charm and unpredictability to their budding relationship.
Set against vibrant cityscapes and backed by a lively soundtrack, the film embraces the beauty of imperfection. Each humorous twist and heartfelt moment reminds us that love is an unscripted journey—one where every mishap can become a cherished memory and every smile leads to a deeper connection.', '2025-01-15', 121, 'http://images.kinodev.localhost/1020.png');
